import { Search, ShoppingBag, UserRound } from 'lucide-react';
import { Benefits, Footer, Hero, ProductRail, TileGrid } from './ui';

const deals = [
  { name:'Pulse Pods Mini', detail:'42-hour playback', price:'₹1,249', compareAt:'₹3,999', badge:'68% OFF', tone:'violet' },
  { name:'Orbit Call', detail:'Bluetooth calling', price:'₹1,499', compareAt:'₹5,499', badge:'72% OFF', tone:'mint' },
  { name:'Rush Band', detail:'Deep bass mode', price:'₹899', compareAt:'₹2,799', badge:'67% OFF', tone:'red' },
  { name:'Drift Speaker', detail:'12W room-filling sound', price:'₹1,699', compareAt:'₹3,999', badge:'57% OFF', tone:'blue' },
  { name:'Volt Bank', detail:'20,000mAh reserve', price:'₹1,599', compareAt:'₹4,499', badge:'64% OFF', tone:'yellow' },
];

export function BoatShowcase() {
  return <section className="reference boat" aria-labelledby="boat-title"><div className="reference-label boat-label"><span>Reference 02</span><h1 id="boat-title">High-energy tech retail</h1><p>Structure study inspired by boAt</p></div><div className="boat-sale">THE BIG SOUND WEEK IS ON · <a href="#">SHOP THE DROP</a></div><header className="boat-nav"><a className="wordmark" href="#">auda<span>x</span></a><nav><a href="#">Categories⌄</a><a href="#">Personalise</a><a href="#">Gifting</a><a href="#">More⌄</a></nav><label><Search/><input aria-label="Search" placeholder="Search sound, wearables & more"/></label><UserRound/><ShoppingBag/></header><Hero eyebrow="LIMITED-TIME DROP" title="TURN UP YOUR EVERYDAY" body="Big sound. Bold color. Prices that move fast." actions={[{label:'SHOP NOW'}]} tone="electric"/><Benefits items={[{symbol:'12+',title:'Extended cover',detail:'Months of assurance'},{symbol:'GST',title:'Business billing',detail:'Invoice ready'},{symbol:'→',title:'Express delivery',detail:'Across serviceable areas'},{symbol:'7D',title:'Easy replacement',detail:'Seven-day window'}]}/><ProductRail title="Deals are live" products={deals} accent="red"/><ProductRail title="Big audio energy" products={deals.slice(1)} accent="red" tabs={['All deals','Earbuds','Watches','Speakers']}/><TileGrid title="Shop by category" columns={5} tiles={[{title:'Earbuds',tone:'violet'},{title:'Neckbands',tone:'red'},{title:'Smartwatches',tone:'mint'},{title:'Speakers',tone:'blue'},{title:'Power',tone:'yellow'}]}/><ProductRail title="Top picks for you" products={[...deals].reverse()} accent="red" tabs={['New launches','Personalised']}/><TileGrid title="Shop by lifestyle" columns={4} tiles={[{title:'For movement',action:'View all',tone:'lime'},{title:'For parties',action:'View all',tone:'violet'},{title:'For focus',action:'View all',tone:'blue'},{title:'For detail',action:'View all',tone:'orange'}]}/><ProductRail title="Crowd favorites" products={deals} accent="red" tabs={['Best sellers','Home audio','Top earbuds','Top watches']}/><Footer title="Get the signal" description="New launches, sharp offers, and listening tips - sent occasionally." groups={[{title:'Shop',links:['Earbuds','Headphones','Speakers','Smartwatches']},{title:'Help',links:['Track an order','Warranty & support','Replacement policy']},{title:'Company',links:['Our story','Newsroom','Careers']}]} /></section>;
}
